### ISSUE TITLE
unit test: TestUpdateInfoSuccess() fails if using accountId = 11087

### ISSUE THREAD

**Issue by fudgebucket27** [taranasus/LoopringAPI#10]
The unit test 'TestUpdateInfoSuccess()' fails with the following error " Newtonsoft.Json.JsonSerializationException: Error converting value "" to type 'System.Numerics.BigInteger'. Path 'transactions[4].feeAmount', line 1, position 1568. ---> System.ArgumentException: Could not cast or convert from System.String to System.Numerics.BigInteger." when using my account id 11087 in UAT environment. This is because the feeAmount in the response is a string not a number.

Changing this type to string for this property resolves the issue: https://github.com/taranasus/LoopringSharp/blob/1ebb723d40de695327d2d7d88fd3effa4afc31c8/LoopringAPI/Models/ApiTransaction.cs#L12

**Comment by taranasus** [comment]
Fixed as proposed in nuget https://www.nuget.org/packages/LoopringSharp/0.3.3
