### ISSUE TITLE
Issue with running LoopringSharp.TestConsole

### ISSUE THREAD

**Issue by fudgebucket27** [taranasus/LoopringAPI#5]
When trying to run the LoopringSharp.TestConsole project, The nuget build task ( file, NuGet.Build.Tasks.Pack.targets) is throwing an error: "Could not find a part of the path 'C:\Downloads'" . When I create this directory it then throws the error "File not found: 'C:\Downloads\loopringsharp.png'" .

**Comment by fudgebucket27** [comment]
I've put in a dummy png with the same file name as a workaround for now

**Comment by taranasus** [comment]
My bad, I made a commit now which should fix it
