### ISSUE TITLE
Relayer timestamp should be an object?

### ISSUE THREAD

**Issue by fudgebucket27** [taranasus/LoopringAPI#8]
I feel that there should be a proper object for the relayer timestamp instead of just returning long? 

https://github.com/taranasus/LoopringSharp/blob/d8d0f92b64c969066e3fdec4b7be27801242fcb2/LoopringAPI/Client.cs#L114-L117

Something like
```csharp
public class RelayerTimestamp
{
  public long timestamp {get;set;}
}
```

**Comment by taranasus** [comment]
Towards what end? The reason everything else returns a class is because it returns multiple values. This returns just one simple timestamp.

**Comment by fudgebucket27** [comment]
That's fair. I just like having objects to match the Json response back haha. Close this then
